# Generated by Django 2.1.5 on 2019-03-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
