# Generated by Django 2.1.5 on 2019-03-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0003_category_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='number_of_searches',
            field=models.IntegerField(default=0),
        ),
    ]
