# Generated by Django 2.1.5 on 2019-03-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0004_category_number_of_searches'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='number_of_products',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
