# Generated by Django 2.1.5 on 2019-03-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0005_auto_20190310_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_number_of_product',
            field=models.IntegerField(default=0),
        ),
    ]
