# Generated by Django 2.1.5 on 2019-03-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0006_category_total_number_of_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
